import libreria

assert (libreria.validar_nombre("ROSA")== True)
assert (libreria.validar_nombre("PATRICK")== True)
assert (libreria.validar_nombre("ANA")== False)
assert (libreria.validar_nombre("111")== False)
assert (libreria.validar_nombre("ANDRE")== True)
print("validar_nombre ok")

assert (libreria.validar_la_letra("G")== False)
assert (libreria.validar_la_letra("Q")== False)
assert (libreria.validar_la_letra("A")== True)
assert (libreria.validar_la_letra("FF")== False)
assert (libreria.validar_la_letra("D")== False)
print("validar_la_letra ok")

assert (libreria.validar_entero("12")== True)
assert (libreria.validar_entero("4")== True)
assert (libreria.validar_entero("34.6")== True)
assert (libreria.validar_entero("2")== True)
assert (libreria.validar_entero("0")== True)
print("validar_entero ok")

assert (libreria.es_hexadecimal("T") == False)
assert (libreria.es_hexadecimal("B") == True)
assert (libreria.es_hexadecimal("MM") == False)
assert (libreria.es_hexadecimal("Q") == False)
assert (libreria.es_hexadecimal("G") == False)
print ("es_hexadecimal OK")


assert (libreria.validar_rgb(" #3456?") == False)
assert (libreria.validar_rgb("#0011FG") == False)
assert (libreria.validar_rgb("FF00FFEE") == False)
assert (libreria.validar_rgb("00000000") == False)
assert (libreria.validar_rgb ("#FFFFF") == False)
print("validar_rgb ok")

assert (libreria.es_bit("A") == False)
assert (libreria.es_bit("J") == False)
assert (libreria.es_bit("5") == False)
assert (libreria.es_bit("1") == True)
assert (libreria.es_bit("0") == True)
print("es_bit ok")

assert (libreria.es_byte("00000000") == False)
assert (libreria.es_byte("11111111") == False)
assert (libreria.es_byte("ABC") == False)
assert (libreria.es_byte("555555555") == False)
assert (libreria.es_byte("CMTHFRE") == False)
print("es_byte ok")

assert (libreria.es_sexo_valido("J") == False)
assert (libreria.es_sexo_valido("X") == False)
assert (libreria.es_sexo_valido("F") == True)
assert (libreria.es_sexo_valido("f") == False)
assert (libreria.es_sexo_valido("M") == True)
print("es_sexo_valido ok")

assert (libreria.calificar(1) == "Muy Bajo")
assert (libreria.calificar(5) == "Bajo")
assert (libreria.calificar(13) == "Regular")
assert (libreria.calificar(18) == "Bien")
assert (libreria.calificar(20) == "Excelente")
print("calificar ok")

b=15
a=12
area=libreria.area_triangulo(b,a)
print(area)

assert (libreria.producto("gelatina")== "GELATINA")
assert (libreria.producto("cocoa")== "cocoa")
assert (libreria.producto("cafe")== "cafe")
assert (libreria.producto("chocolate")== "chocolate")
assert (libreria.producto("galleta")== "galleta")
print("producto ok")

assert (libreria.sumar(1,8)== 9)
assert (libreria.sumar(-2,5)== 3)
assert (libreria.sumar(1,1)== 2)
assert (libreria.sumar(10,12)== 22)
assert (libreria.sumar(-7,11)== 4)
print("sumar ok")

assert (libreria.cris("sonrisa")== "sonrisa")
assert (libreria.cris("")== "")
assert (libreria.cris("armonia ")== "armonia ")
assert (libreria.cris("sedfrt")== "sedfrt")
assert (libreria.cris(" suena")== " suena")
print("cris ok")

assert (libreria.definir("BETZY")== "betzy")
assert (libreria.definir("lote")== "lote")
assert (libreria.definir("armonia ")== "armonia ")
assert (libreria.definir("sedfrt")== "sedfrt")
assert (libreria.definir(" suena")== " suena")
print("definir ok")

assert (libreria.yo("cariño")== "CARIÑO")
assert (libreria.yo("casa")== "casa")
assert (libreria.yo("sol")== "sol")
assert (libreria.yo("espejo")== "espejo")
assert (libreria.yo("matrimonio")== "matrimonio")
print("yo ok")
